restore test summary

diff --git a/.github/workflows/test-reporter-multijobs-regroup-reports.yml b/.github/workflows/test-reporter-multijobs-regroup-reports.yml
--- a/.github/workflows/test-reporter-multijobs-regroup-reports.yml
+++ b/.github/workflows/test-reporter-multijobs-regroup-reports.yml
@@ -363,183 +363,6 @@ jobs:
           name: surefire-reports-group-b
           path: ${{ github.workspace }}/results/groupB/surefire-reports/
 
-#      - name: Delete Artifacts reports C and D
-#        id: delete_artifacts
-#        uses: actions/github-script@v6
-#        with:
-#          github-token: ${{ secrets.GITHUB_TOKEN }}
-#          debug: true
-#          retries: 2
-#          script: |
-#            const artifactNamesToDelete = ['extent-reports-test-bundleC', 'extent-reports-test-bundleD', 'surefire-reports-test-bundleC', 'surefire-reports-test-bundleD'];
-#
-#            const response = await github.rest.actions.listWorkflowRunArtifacts({
-#              owner: context.repo.owner,
-#              repo: context.repo.repo,
-#              run_id: context.runId
-#            });
-#
-#            console.log(JSON.stringify(response));
-#
-#            response.data.artifacts
-#              .forEach(({ id, name}) => {
-#              if (artifactNamesToDelete.includes(name)) {
-#                console.log("id: " + id + " name: " + name);
-#              }
-#            });
-            
-#            const deletionPromises = response.data.artifacts
-#              .filter(({ name }) => artifactNamesToDelete.includes(name))
-#              .map(({ id, name }) => {
-#                console.log("Deleting Artifact id: " + id + " name: " + name);
-#                return github.rest.actions.deleteArtifact({
-#                  owner: context.repo.owner,
-#                   repo: context.repo.repo,
-#                   artifact_id: id
-#                });
-#              });
-#
-#            const deletionResponses = await Promise.all(deletionPromises);
-#            console.log("Deletion responses:", JSON.stringify(deletionResponses));
-#
-#            response.data.artifacts
-#              .forEach(({ id, name}) => {
-#              if (artifactNamesToDelete.includes(name)) {
-#                console.log("Deleting Artifact id: " + id + " name: " + name);
-#                await github.rest.actions.deleteArtifact({
-#                  owner: context.repo.owner,
-#                  repo: context.repo.repo,
-#                  artifact_id: id
-#                });
-#              }
-#            });
-            
-            
-            
-#            if (response.artifacts && Array.isArray(response.artifacts)) {
-#              console.log("IDs of all artifacts:");
-#              response.artifacts.forEach(artifact => {
-#                if (artifact.id !== undefined) {
-#                  console.log(artifact.id);
-#                }
-#              });
-#            } else {
-#                console.log("No artifacts found in the response.");
-#            }
-
-#            console.log('Deleting artifacts from workflow run ' + context.runId);
-#
-#            for (const artifact of artifacts.data.artifacts) {
-#            console.log('Artifact id: ' + artifact.id + ', name: ' + artifact.name);
-#              if (artifactNamesToDelete.includes(artifact.name)) {
-#                await github.rest.actions.deleteArtifact({
-#                  owner: context.repo.owner,
-#                  repo: context.repo.repo,
-#                  artifact_id: artifact.id
-#                });
-#              }
-#            }
-          
-#      - name: Get Display Delete Artifacts Result
-#        run: |
-#          echo "${{ steps.delete_artifacts.outputs.result }}"
-
-
-
-#  capture-run-id:
-#    runs-on: ubuntu-latest
-#    steps:
-#    - name: Capture Run ID
-#      id: capture-run-id
-#      run: |
-#        echo "Run ID: ${{ github.run_id }}" > run-id.txt
-#
-#    - name: Upload Run ID Artifact
-#      uses: actions/upload-artifact@v2
-#      with:
-#        name: run-id-artifact
-#        path: run-id.txt
-
-#            const runsResponse = await github.request("GET /repos/${{ github.repository }}/actions/runs")
-#            for (workflow_run of runsResponse.data.workflow_runs) {
-#              if (workflow_run.name == "${{ github.workflow }}" && workflow_run.status !== "in_progress") {
-#                console.log(`Deleting artifacts from workflow run ${workflow_run.id}`)
-#                const response = await github.request(`GET /repos/$/actions/runs/${workflow_run.id}/artifacts`)
-#                // Define the names of the artifacts to delete
-#                const artifactNamesToDelete = ['extent-reports-test-bundleC', 'extent-reports-test-bundleD', 'surefire-reports-test-bundleC', 'surefire-reports-test-bundleD'];
-#
-#                for (artifact of response.data.artifacts) {
-#                  if (artifactNamesToDelete.includes(artifact.name)) {
-#                    console.log(`Deleting artifact with id ${artifact.id}`)
-#                    const deleteResponse = await github.request(`DELETE /repos/$/actions/artifacts/${artifact.id}`)
-#                  }
-#                }
-#              }
-#            }
-
-#              const { data: artifacts } = github.rest.actions.listWorkflowRunArtifacts({
-#                owner: context.repo.owner,
-#                repo: context.repo.repo,
-#                run_id: ${{ github.run_id }}
-#              });
-#                // Check if 'artifacts' is defined
-#              if (artifacts && artifacts.artifacts) {
-#                // Define the names of the artifacts to delete
-#                const artifactNamesToDelete = ['extent-reports-test-bundleC', 'extent-reports-test-bundleD', 'surefire-reports-test-bundleC', 'surefire-reports-test-bundleD'];
-#
-#                for (const artifact of artifacts.artifacts) {
-#                  if (artifactNamesToDelete.includes(artifact.name)) {
-#                    await github.rest.actions.deleteArtifact({
-#                      owner: context.repo.owner,
-#                      repo: context.repo.repo,
-#                      artifact_id: artifact.id
-#                  });
-#                }
-#              }
-#            } else{
-#            console.log('No artifacts found for the current workflow run.');
-#            }
-
-#      - name: Delete old artifacts
-#        uses: actions/github-script@v4
-#        with:
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
-#          script: |
-#            const ctx = context;
-#            const artifacts = ctx.github.rest.repos.artifact.nodes.list({
-#            'owner': ctx.repo.owner,
-#            'repo': ctx.repo.repo,
-#            });
-#            for (const artifact of artifacts) {
-#              if (artifact.name === 'extent-reports-test-bundleC' || artifact.name === 'extent-reports-test-bundleD') {
-#                ctx.github.rest.repos.artifact.nodes.delete({
-#                'owner': ctx.repo.owner,
-#                'repo': ctx.repo.repo,
-#                'artifact_id': artifact.id,
-#                });
-#              }
-#            }
-
-          #    - name: Delete artifacts extent reports C
-#      uses: actions/delete-artifact@v2
-#      with:
-#        name: extent-reports-test-bundleC
-#
-#    - name: Delete artifact extent reports D
-#      uses: actions/delete-artifact@v2
-#      with:
-#        name: extent-reports-test-bundleD
-#
-#    - name: Delete artifacts surefire reports C
-#      uses: actions/delete-artifact@v2
-#      with:
-#        name: surefire-reports-test-bundleC
-#
-#    - name: Delete artifact surefire reports D
-#      uses: actions/delete-artifact@v2
-#      with:
-#        name: surefire-reports-test-bundleD
-
           #      - name: Upload test reports
           #        if: success() || failure()
           #        uses: actions/upload-artifact@v3
@@ -563,46 +386,61 @@ jobs:
 
           #  ./target/surefire-reports/TEST*.xml
 
-        #      - name: Publish Test Report
-        #        id: publish_report
-        #        uses: dorny/test-reporter@v1
-        #        if: success() || failure() # always run even if the previous step fails
-        #        with:
-        #          name: Test Report
-        #          reporter: java-junit
-        #          only-summary: false
-        #          list-suites: all
-        #          list-tests: all
-        #          fail-on-error: false
-        #          path: '**/target/surefire-reports/junitreports/TEST-*.xml'
+  publish_report_summary:
+    if: |
+      (${{ success() }} || ${{ failure() }})
+      needs.test_group_a.outputs.test_results_output == 'success'
+      && needs.test_bundle_c.outputs.test_results_output == 'success'
+      && needs.test_bundle_d.outputs.test_results_output == 'success'
+    needs: [ test_group_a, test_bundle_c, test_bundle_d ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Publish Test Report
+        id: publish_report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # always run even if the previous step fails
+        with:
+         name: Test Report
+         reporter: java-junit
+         only-summary: true
+         list-suites: all
+         list-tests: none
+         fail-on-error: false
+         path: '**/target/surefire-reports/TEST-*.xml'
+
+
+        # path: '**/target/surefire-reports/junitreports/TEST-*.xml'
 
         #  path: '**/target/surefire-reports/TEST-*.xml'
 
-        #      - name: Print Test Report Output
-        #        if: success() || failure()
-        #        run: |
-        #          echo "url: ${{ steps.publish_report.outputs.url }}"
-        #          echo "url_html: ${{ steps.publish_report.outputs.url_html }}"
-        #          echo "Passed count: ${{ steps.publish_report.outputs.passed }}"
-        #          echo "Failed count: ${{ steps.publish_report.outputs.failed }}"
-        #          echo "Skipped count: ${{ steps.publish_report.outputs.skipped }}"
-        #          echo "Execution time ms: ${{ steps.publish_report.outputs.time }}"
-        #
-        #      - name: Test Results Summary
-        #        id: test_summary
-        #        if: success() || failure()
-        #        run: |
-        #          passed=${{ steps.publish_report.outputs.passed }}
-        #          failed=${{ steps.publish_report.outputs.failed }}
-        #          skipped=${{ steps.publish_report.outputs.skipped }}
-        #          total=$((passed+failed+skipped))
-        #          echo "### Test Results Summary :rocket:" >> $GITHUB_STEP_SUMMARY
-        #          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
-        #          echo "Total: $total" >> $GITHUB_STEP_SUMMARY
-        #          echo ":heavy_check_mark: Passed: ${{ steps.publish_report.outputs.passed }} " >> $GITHUB_STEP_SUMMARY
-        #          echo ":x: Failed: ${{ steps.publish_report.outputs.failed }}" >> $GITHUB_STEP_SUMMARY
-        #          echo ":white_circle: Skipped: ${{ steps.publish_report.outputs.skipped }}" >> $GITHUB_STEP_SUMMARY
-        #          echo "Execution time (ms): ${{ steps.publish_report.outputs.time }}" >> $GITHUB_STEP_SUMMARY
+      - name: Print Test Report Output
+        if: success() || failure()
+        run: |
+          echo "url: ${{ steps.publish_report.outputs.url }}"
+          echo "url_html: ${{ steps.publish_report.outputs.url_html }}"
+          echo "Passed count: ${{ steps.publish_report.outputs.passed }}"
+          echo "Failed count: ${{ steps.publish_report.outputs.failed }}"
+          echo "Skipped count: ${{ steps.publish_report.outputs.skipped }}"
+          echo "Execution time ms: ${{ steps.publish_report.outputs.time }}"
+
+      - name: Test Results Summary
+        id: test_summary
+        if: success() || failure()
+        run: |
+          passed=${{ steps.publish_report.outputs.passed }}
+          failed=${{ steps.publish_report.outputs.failed }}
+          skipped=${{ steps.publish_report.outputs.skipped }}
+          total=$((passed+failed+skipped))
+          echo "### Test Results Summary :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
+          echo "Total: $total" >> $GITHUB_STEP_SUMMARY
+          echo ":heavy_check_mark: Passed: ${{ steps.publish_report.outputs.passed }} " >> $GITHUB_STEP_SUMMARY
+          echo ":x: Failed: ${{ steps.publish_report.outputs.failed }}" >> $GITHUB_STEP_SUMMARY
+          echo ":white_circle: Skipped: ${{ steps.publish_report.outputs.skipped }}" >> $GITHUB_STEP_SUMMARY
+          echo "Execution time (ms): ${{ steps.publish_report.outputs.time }}" >> $GITHUB_STEP_SUMMARY
 
         #      - name: Setup Pages
         #        id: pages
