regroup reports

diff --git a/.github/workflows/test-reporter-multijobs-regroup-reports.yml b/.github/workflows/test-reporter-multijobs-regroup-reports.yml
--- a/.github/workflows/test-reporter-multijobs-regroup-reports.yml
+++ b/.github/workflows/test-reporter-multijobs-regroup-reports.yml
@@ -1,4 +1,3 @@
-
 name: test-reporter-multi-jobs-regroup-reports
 on:
   workflow_dispatch:
@@ -144,16 +143,16 @@ jobs:
       - name: Run tests BundleC
         run: mvn test -DsuiteXmlFile="$GITHUB_WORKSPACE/src/test/testsuite/bundleCTest.xml"
 
-#      - name: Copy test results
-#        id: copy_test_results
-#        if: success() || failure()
-#        run: |
-#          mkdir -p $GITHUB_WORKSPACE/results/groupB/bundleC
-#          cp -r target/surefire-reports $GITHUB_WORKSPACE/results/groupB/bundleC/
-#          cp -r target/reports $GITHUB_WORKSPACE/results/groupB/bundleC/
-#          ls -R $GITHUB_WORKSPACE/results/groupB/bundleC/
-#        env:
-#          GROUPB_RESULTS_DIR: ${{ github.workspace }}/results/groupB
+      #      - name: Copy test results
+      #        id: copy_test_results
+      #        if: success() || failure()
+      #        run: |
+      #          mkdir -p $GITHUB_WORKSPACE/results/groupB/bundleC
+      #          cp -r target/surefire-reports $GITHUB_WORKSPACE/results/groupB/bundleC/
+      #          cp -r target/reports $GITHUB_WORKSPACE/results/groupB/bundleC/
+      #          ls -R $GITHUB_WORKSPACE/results/groupB/bundleC/
+      #        env:
+      #          GROUPB_RESULTS_DIR: ${{ github.workspace }}/results/groupB
 
       - name: Upload extent reports
         if: success() || failure()
@@ -209,16 +208,16 @@ jobs:
       - name: Run tests BundleD
         run: mvn test -DsuiteXmlFile="$GITHUB_WORKSPACE/src/test/testsuite/bundleDTest.xml"
 
-#      - name: Copy test results
-#        id: copy_test_results
-#        if: success() || failure()
-#        run: |
-#          mkdir -p $GITHUB_WORKSPACE/results/groupB/bundleD
-#          cp -r target/surefire-reports $GITHUB_WORKSPACE/results/groupB/bundleD/
-#          cp -r target/reports $GITHUB_WORKSPACE/results/groupB/bundleD/
-#          ls -R $GITHUB_WORKSPACE/results/groupB/bundleD/
-#        env:
-#          GROUPB_RESULTS_DIR: ${{ github.workspace }}/results/groupB
+      #      - name: Copy test results
+      #        id: copy_test_results
+      #        if: success() || failure()
+      #        run: |
+      #          mkdir -p $GITHUB_WORKSPACE/results/groupB/bundleD
+      #          cp -r target/surefire-reports $GITHUB_WORKSPACE/results/groupB/bundleD/
+      #          cp -r target/reports $GITHUB_WORKSPACE/results/groupB/bundleD/
+      #          ls -R $GITHUB_WORKSPACE/results/groupB/bundleD/
+      #        env:
+      #          GROUPB_RESULTS_DIR: ${{ github.workspace }}/results/groupB
 
       - name: Upload extent reports
         if: success() || failure()
@@ -265,68 +264,68 @@ jobs:
   #    runs-on: ubuntu-latest
   #    steps:
 
-#  upload_reports_group_a:
-#    if: |
-#      (${{ success() }} || ${{ failure() }})
-#      needs.test_group_a.outputs.test_results_output == 'success'
-#    needs: test_group_a
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v3
-#
-#      - name: check reports directory
-#        id: check_reports_dir
-#        if: success() || failure()
-#        run: |
-#          ls -R $GITHUB_WORKSPACE/results/groupA/
-#
-#        #          cp -r target/surefire-reports ${{ github.workspace }}/results/groupA
-#        #          cp -r target/reports ${{ github.workspace }}/results/groupA
-#        #          cd ${{ github.workspace }}/results/groupA/target/surefire-reports
-#        #          ls
-#
-#      - name: Upload extent reports
-#        if: success() || failure()
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: extent-reports-group-a
-#          path: ${{ github.workspace }}/results/groupA/reports/
-#          if-no-files-found: error
-#
-#      - name: Upload surefire reports
-#        if: success() || failure()
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: surefire-reports-group-a
-#          path: ${{ github.workspace }}/results/groupA/surefire-reports/
-#          if-no-files-found: error
+  #  upload_reports_group_a:
+  #    if: |
+  #      (${{ success() }} || ${{ failure() }})
+  #      needs.test_group_a.outputs.test_results_output == 'success'
+  #    needs: test_group_a
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Checkout code
+  #        uses: actions/checkout@v3
+  #
+  #      - name: check reports directory
+  #        id: check_reports_dir
+  #        if: success() || failure()
+  #        run: |
+  #          ls -R $GITHUB_WORKSPACE/results/groupA/
+  #
+  #        #          cp -r target/surefire-reports ${{ github.workspace }}/results/groupA
+  #        #          cp -r target/reports ${{ github.workspace }}/results/groupA
+  #        #          cd ${{ github.workspace }}/results/groupA/target/surefire-reports
+  #        #          ls
+  #
+  #      - name: Upload extent reports
+  #        if: success() || failure()
+  #        uses: actions/upload-artifact@v3
+  #        with:
+  #          name: extent-reports-group-a
+  #          path: ${{ github.workspace }}/results/groupA/reports/
+  #          if-no-files-found: error
+  #
+  #      - name: Upload surefire reports
+  #        if: success() || failure()
+  #        uses: actions/upload-artifact@v3
+  #        with:
+  #          name: surefire-reports-group-a
+  #          path: ${{ github.workspace }}/results/groupA/surefire-reports/
+  #          if-no-files-found: error
 
   upload_reports_group_b:
     if: |
       (${{ success() }} || ${{ failure() }})
       needs.test_bundle_c.outputs.test_results_output == 'success'
       && needs.test_bundle_d.outputs.test_results_output == 'success'
-    needs: [test_bundle_c, test_bundle_d]
+    needs: [ test_bundle_c, test_bundle_d ]
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      #      - name: Checkout code
+      #        uses: actions/checkout@v3
 
       - name: Download and bundle artifacts extend reports C and D into groupB
-        run: |          
-          mkdir -p results/groupB/extent-reports
+        run: |
+               mkdir -p results/groupB/extent-reports
           
-        # Download and extract artifacts C and D
-          echo "Downloading and extracting artifact ..."          
-          echo "::set-output name=extent-reports-test-bundleC::${{ steps.test_bundle_c.outputs.extent-reports-test-bundleC }}"
-          echo "::set-output name=extent-reports-test-bundleD::${{ steps.test_bundle_d.outputs.extent-reports-test-bundleD }}"
-         
-        # Bundle artifacts C and D into groupB
-          cp -r ${{ steps.test_bundle_c.outputs.extent-reports-test-bundleC }}/* results/groupB/extent-reports/
-          cp -r ${{ steps.test_bundle_d.outputs.extent-reports-test-bundleD }}/* results/groupB/extent-reports/               
-
-        shell: bash
+          # Download and extract artifacts C and D
+               echo "Downloading and extracting artifact ..."
+               echo "::set-output name=extent-reports-test-bundleC::${{ steps.test_bundle_c.outputs.extent-reports-test-bundleC }}"
+               echo "::set-output name=extent-reports-test-bundleD::${{ steps.test_bundle_d.outputs.extent-reports-test-bundleD }}"
+          
+          # Bundle artifacts C and D into groupB
+               cp -r ${{ steps.test_bundle_c.outputs.extent-reports-test-bundleC }}/* results/groupB/extent-reports/
+               cp -r ${{ steps.test_bundle_d.outputs.extent-reports-test-bundleD }}/* results/groupB/extent-reports/
+               
+               shell: bash
 
       - name: Upload extent reports
         if: success() || failure()
@@ -337,19 +336,19 @@ jobs:
           if-no-files-found: error
 
       - name: Download and bundle artifacts surefire reports C and D into groupB
-        run: |            
-          mkdir -p results/groupB/surefire-reports
-            
-        # Download and extract artifacts C and D
-          echo "Downloading and extracting artifact ..."
-          echo "::set-output name=surefire-reports-test-bundleC::${{ steps.test_bundle_c.outputs.surefire-reports-test-bundleC }}"
-          echo "::set-output name=surefire-reports-test-bundleD::${{ steps.test_bundle_d.outputs.surefire-reports-test-bundleD }}"
-            
-        # Bundle artifacts C and D into groupB
-          cp -r ${{ steps.test_bundle_c.outputs.surefire-reports-test-bundleC }}/* results/groupB/surefire-reports/
-          cp -r ${{ steps.test_bundle_d.outputs.surefire-reports-test-bundleD }}/* results/groupB/surefire-reports/
+        run: |
+               mkdir -p results/groupB/surefire-reports
           
-        shell: bash
+          # Download and extract artifacts C and D
+               echo "Downloading and extracting artifact ..."
+               echo "::set-output name=surefire-reports-test-bundleC::${{ steps.test_bundle_c.outputs.surefire-reports-test-bundleC }}"
+               echo "::set-output name=surefire-reports-test-bundleD::${{ steps.test_bundle_d.outputs.surefire-reports-test-bundleD }}"
+          
+          # Bundle artifacts C and D into groupB
+               cp -r ${{ steps.test_bundle_c.outputs.surefire-reports-test-bundleC }}/* results/groupB/surefire-reports/
+               cp -r ${{ steps.test_bundle_d.outputs.surefire-reports-test-bundleD }}/* results/groupB/surefire-reports/
+               
+               shell: bash
 
       - name: Upload surefire reports
         if: success() || failure()
